### ISSUE TITLE
Error occured in Behavior

### ISSUE THREAD

**Issue by kaibadash** [rollbar/rollbar-php#420]
We are trying rollba-php v1.6.3 with CakePHP3.5.16 and PHP 7.0.21.

We were not able to find the CakePHP’s quick tutorial in docs.
https://docs.rollbar.com/docs/php#section-quick-start .

I edited bootstrap.php like that:

```
Rollbar::init(
  array(
    'access_token' => 'MY_TOKEN',
    'environment' => env('CAKE_ENV'),
    "root" => "/" . basename(dirname(APP))
  )
);
```

And I overrided ErrorHandler.

```php
class AppErrorHandlerMiddleware extends ErrorHandlerMiddleware
{
    public function handleException($exception, $request, $response)
    {
        if (env('CAKE_ENV') == "production") {
            Rollbar::log(Level::ERROR, $exception, [$request, $response]);
        }
        parent::handleException($exception, $request, $response);
    }

    protected function handleInternalError($response)
    {
        if (env('CAKE_ENV') == "production") {
            Rollbar::log(Level::ERROR, $response);
        }
        parent::handleInternalError($response);
    }
}
```

Is that OK?
We still got an error in a Behavior function.

```
2018-10-29 13:37:33 Error: [PDOException] You cannot serialize or unserialize PDO instances
Request URL: /xxx/edit/6253
Referer URL: http://localhost/xxx/edit/6253
Stack Trace:
#0 [internal function]: PDO->__sleep()
#1 /srv/vendor/rollbar/rollbar/src/Utilities.php(81): ArrayObject->serialize()
#2 /srv/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array)
#3 /srv/vendor/rollbar/rollbar/src/Payload/Frame.php(108): Rollbar\Utilities::serializeForRollbar(Array)
#4 /srv/vendor/rollbar/rollbar/src/Utilities.php(81): Rollbar\Payload\Frame->serialize()
#5 /srv/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array)
#6 /srv/vendor/rollbar/rollbar/src/Payload/Trace.php(49): Rollbar\Utilities::serializeForRollbar(Array)
#7 /srv/vendor/rollbar/rollbar/src/Utilities.php(81): Rollbar\Payload\Trace->serialize()
#8 /srv/vendor/rollbar/rollbar/src/Payload/Body.php(32): Rollbar\Utilities::serializeForRollbar(Array)
#9 /srv/vendor/rollbar/rollbar/src/Utilities.php(81): Rollbar\Payload\Body->serialize()
#10 /srv/vendor/rollbar/rollbar/src/Payload/Data.php(253): Rollbar\Utilities::serializeForRollbar(Array)
#11 /srv/vendor/rollbar/rollbar/src/Utilities.php(81): Rollbar\Payload\Data->serialize()
#12 /srv/vendor/rollbar/rollbar/src/Payload/Payload.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#13 /srv/vendor/rollbar/rollbar/src/RollbarLogger.php(94): Rollbar\Payload\Payload->serialize()
#14 /srv/vendor/rollbar/rollbar/src/Handlers/ErrorHandler.php(47): Rollbar\RollbarLogger->log('error', Object(Rollbar\ErrorWrapper), Array, true)
#15 [internal function]: Rollbar\Handlers\ErrorHandler->handle(2, 'fclose(): suppl...', '/srv/src/Upload...', 128, Array)
#16 /srv/src/Upload/File/Writer/ExtentionNormalizationWriter.php(128): fclose(Resource id #1378)
#17 /srv/src/Upload/File/Writer/ExtentionNormalizationWriter.php(82): App\Upload\File\Writer\ExtentionNormalizationWriter->writeFile(Object(League\Flysystem\Filesystem), '/tmp/baseeWKRNr', 'XXX/6253/3b...')
#18 /srv/src/Model/Behavior/Base64FileUploadBehavior.php(38): App\Upload\File\Writer\ExtentionNormalizationWriter->write(Array)
#19 /srv/vendor/cakephp/cakephp/src/Event/EventManager.php(416): App\Model\Behavior\Base64FileUploadBehavior->beforeSave(Object(Cake\Event\Event), Object(App\Model\Entity\JsonInvestImage), Object(ArrayObject))
#20 /srv/vendor/cakephp/cakephp/src/Event/EventManager.php(393): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#21 /srv/vendor/cakephp/cakephp/src/Event/EventDispatcherTrait.php(110): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#22 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1802): Cake\ORM\Table->dispatchEvent('Model.beforeSav...', Array)
#23 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1736): Cake\ORM\Table->_processSave(Object(App\Model\Entity\JsonInvestImage), Object(ArrayObject))
#24 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1459): Cake\ORM\Table->Cake\ORM\{closure}()
#25 /srv/vendor/cakephp/cakephp/src/Database/Connection.php(682): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#26 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1460): Cake\Database\Connection->transactional(Object(Closure))
#27 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1737): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#28 /srv/vendor/cakephp/cakephp/src/ORM/Association/HasMany.php(239): Cake\ORM\Table->save(Object(App\Model\Entity\JsonInvestImage), Object(ArrayObject))
#29 /srv/vendor/cakephp/cakephp/src/ORM/Association/HasMany.php(200): Cake\ORM\Association\HasMany->_saveTarget(Array, Object(App\Model\Entity\Invest), Array, Array)
#30 /srv/vendor/cakephp/cakephp/src/ORM/AssociationCollection.php(274): Cake\ORM\Association\HasMany->saveAssociated(Object(App\Model\Entity\Invest), Array)
#31 /srv/vendor/cakephp/cakephp/src/ORM/AssociationCollection.php(248): Cake\ORM\AssociationCollection->_save(Object(Cake\ORM\Association\HasMany), Object(App\Model\Entity\Invest), Array, Array)
#32 /srv/vendor/cakephp/cakephp/src/ORM/AssociationCollection.php(213): Cake\ORM\AssociationCollection->_saveAssociations(Object(App\Model\Table\XXXTable), Object(App\Model\Entity\Invest), Array, Array, true)
#33 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1856): Cake\ORM\AssociationCollection->saveChildren(Object(App\Model\Table\XXXTable), Object(App\Model\Entity\Invest), Array, Array)
#34 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1829): Cake\ORM\Table->_onSaveSuccess(Object(App\Model\Entity\Invest), Object(ArrayObject))
#35 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1736): Cake\ORM\Table->_processSave(Object(App\Model\Entity\Invest), Object(ArrayObject))
#36 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1459): Cake\ORM\Table->Cake\ORM\{closure}()
#37 /srv/vendor/cakephp/cakephp/src/Database/Connection.php(682): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#38 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1460): Cake\Database\Connection->transactional(Object(Closure))
#39 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1737): Cake\ORM\Table->_executeTransaction(Object(Closure), true)
#40 /srv/vendor/cakephp/cakephp/src/ORM/Table.php(1765): Cake\ORM\Table->save(Object(App\Model\Entity\Invest), Object(ArrayObject))
#41 /srv/src/Controller/XXXController.php(452): Cake\ORM\Table->saveOrFail(Object(App\Model\Entity\Invest))
#42 /srv/vendor/cakephp/cakephp/src/Controller/Controller.php(440): App\Controller\XXXController->edit('6253')
#43 /srv/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(119): Cake\Controller\Controller->invokeAction()
#44 /srv/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(93): Cake\Http\ActionDispatcher->_invoke(Object(App\Controller\XXXController))
#45 /srv/vendor/cakephp/cakephp/src/Http/BaseApplication.php(109): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#46 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#47 /srv/vendor/ozee31/cakephp-cors/src/Routing/Middleware/CorsMiddleware.php(31): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#48 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cors\Routing\Middleware\CorsMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#49 /srv/vendor/multidots/cakephp-rest-api/src/Middleware/RestApiMiddleware.php(54): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#50 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): RestApi\Middleware\RestApiMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#51 /srv/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(104): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#52 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#53 /srv/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#54 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#55 /srv/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(98): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#56 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#57 /srv/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#58 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#59 /srv/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#60 /srv/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#61 /srv/webroot/index.php(40): Cake\Http\Server->run()
#62 {main}
```

We have fixed that by removing rollbar .
But we’d like to use rollbar because it is very FANTASTIC, we think.
Do you have any idea?

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look at this?

**Comment by makamo** [comment]
@kaibadash When you initialize the Rollbar object. you need to turn of the auto handler
        Rollbar::init($this->_options, false, false, false);

**Comment by kaibadash** [comment]
Thank you! I'll try that!

**Comment by ArturMoczulski** [comment]
@kaibadash did turning off the autoloader resolve your issue?

**Comment by kaibadash** [comment]
Sorry, I was too busy to check...
I absolutely will do...

**Comment by ArturMoczulski** [comment]
This is most likely due to CakePHP putting PDO objects in the `$response` or `$request` variables you are passing to `\Rollbar\Rollbar::log`. Please make sure, that you either remove those from the data passed Rollbar or convert them into non-PDO objects, like arrays.
