### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException: Error: Uncaught Exception: Cannot rewind a generator that was already run in /vendor/rollbar/rollbar/src/Utilities.php:102

### ISSUE THREAD

**Issue by arendjantetteroo** [rollbar/rollbar-php#429]
Apparently our code uses generators and when an exception occurs somewhere in the stack we get this 500 error due to rollbar trying to rewind such a generator. 

I'm not sure how to debug this as the error in rollbar itself does not show the original stack this happened, it only returns the resulting issue from an E_ERROR. 

Symfony\Component\Debug\Exception\FatalErrorException:
Error: Uncaught Exception: Cannot rewind a generator that was already run in /vendor/rollbar/rollbar/src/Utilities.php:102
Stack trace:
#0 /vendor/rollbar/rollbar/src/Utilities.php(113): Rollbar\Utilities::serializeForRollbar(Object(Generator), NULL, Array, -1, 2)
#1 /vendor/rollbar/rollbar/src/Utilities.php(118): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#2 /vendor/rollbar/rollbar/src/Payload/Frame.php(111): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#3 /vendor/rollbar/rollbar/src/Utilities.php(109): Rollbar\Payload\Frame->serialize()
#4 /vendor/rollbar/rollbar/src/Utilities.php(118): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#5 /vendor/rollbar/rollbar/src/
(Most recent call first)

**Comment by jessewgibbs** [comment]
@ArturMoczulski can you take a look at this?

**Comment by ArturMoczulski** [comment]
Released in `v1.7.3`
