### ISSUE TITLE
Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Routing\CompiledRoute

### ISSUE THREAD

**Issue by Vicftz** [rollbar/rollbar-php#573]
Hi,

I have had this error several times recently in production, throwing a 500 error for my customer.
Is it something on my side or not ?

Here is the stacktrace : 

```
Symfony\Component\ErrorHandler\Error\FatalError:
Uncaught BadMethodCallException: Cannot serialize Symfony\Component\Routing\CompiledRoute in /app/vendor/symfony/routing/CompiledRoute.php:71
Stack trace:
#0 /app/vendor/rollbar/rollbar/src/Utilities.php(152): Symfony\Component\Routing\CompiledRoute->serialize()
#1 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Symfony\Component\Routing\CompiledRoute), NULL, Array, -1, 2)
#2 /app/vendor/rollbar/rollbar/src/Utilities.php(169): Rollbar\Utilities::serializeForRollbar(Object(Illuminate\Routing\Route), NULL, Array, -1, 2)
#3 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Illuminate\Routing\Route), NULL, Array, -1, 1)
#4 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#5 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#6 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#7 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#8 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#9 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#10 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#11 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#12 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#13 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#14 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#15 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#16 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#17 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#18 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#19 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#20 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#21 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#22 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#23 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#24 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#25 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#26 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#27 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#28 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#29 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#30 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#31 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#32 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#33 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#34 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#35 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#36 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#37 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#38 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#39 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#40 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#41 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#42 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#43 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#44 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#45 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#46 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#47 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#48 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#49 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#50 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#51 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#52 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#53 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#54 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#55 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#56 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#57 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#58 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#59 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#60 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#61 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#62 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#63 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#64 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#65 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#66 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#67 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#68 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#69 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#70 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#71 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#72 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#73 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#74 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#75 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#76 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#77 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#78 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#79 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#80 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#81 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#82 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#83 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#84 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#85 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#86 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#87 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#88 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#89 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#90 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#91 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#92 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#93 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#94 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#95 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#96 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#97 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#98 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#99 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#100 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#101 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#102 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#103 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#104 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#105 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#106 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#107 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#108 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#109 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#110 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#111 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#112 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#113 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#114 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#115 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#116 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#117 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#118 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#119 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#120 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#121 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#122 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#123 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#124 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#125 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#126 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#127 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#128 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#129 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#130 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#131 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#132 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#133 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#134 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#135 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#136 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#137 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#138 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#139 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#140 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#141 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#142 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#143 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#144 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#145 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#146 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, -1, 2)
#147 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 2)
#148 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#149 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#150 /app/vendor/rollbar/rollbar/src/Payload/Frame.php(117): Rollbar\Utilities::serializeForRollbarInternal(Array)
#151 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Frame->serialize()
#152 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Frame), NULL, Array, -1, 1)
#153 /app/vendor/rollbar/rollbar/src/Utilities.php(123): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, -1, 1)
#154 /app/vendor/rollbar/rollbar/src/Payload/Trace.php(50): Rollbar\Utilities::serializeForRollbar(Array)
#155 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Trace->serialize()
#156 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Trace), Array, Array, -1, 0)
#157 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, Array, Array)
#158 /app/vendor/rollbar/rollbar/src/Payload/Body.php(49): Rollbar\Utilities::serializeForRollbarInternal(Array, Array)
#159 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Body->serialize()
#160 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Body), NULL, Array, -1, 0)
#161 /app/vendor/rollbar/rollbar/src/Utilities.php(83): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array)
#162 /app/vendor/rollbar/rollbar/src/Payload/Data.php(242): Rollbar\Utilities::serializeForRollbarInternal(Array)
#163 /app/vendor/rollbar/rollbar/src/Utilities.php(155): Rollbar\Payload\Data->serialize()
#164 /app/vendor/rollbar/rollbar/src/Utilities.php(111): Rollbar\Utilities::serializeObject(Object(Rollbar\Payload\Data), NULL, Array, 10, 0)
#165 /app/vendor/rollbar/rollbar/src/Payload/Payload.php(51): Rollbar\Utilities::serializeForRollbar(Array, NULL, Array, 10)
#166 /app/vendor/rollbar/rollbar/src/RollbarLogger.php(127): Rollbar\Payload\Payload->serialize(10)
#167 /app/vendor/rollbar/rollbar/src/Handlers/ExceptionHandler.php(28): Rollbar\RollbarLogger->log('...', Object(BadMethodCallException), Array)
#168 [internal function]: Rollbar\Handlers\ExceptionHandler->handle(Object(BadMethodCallException))
#169 {main}
```

Thank in advance !

**Comment by danielmorell** [comment]
This was fixed by #567 and released in v3.1.3 today.
